### ISSUE TITLE
Config parameter rp.enable = false doesn't work

### ISSUE THREAD

**Issue by pavel-vlasov** [reportportal/agent-java-junit5#44] opened 2020-03-12 10:16 UTC
agent-java-junit5 4.0.1 (last)
Config parameter rp.enable = false doesn't work
Junit   5.4.0

**Comment by HardNorth** [comment] 2020-03-27 13:49
@pavel-vlasov Tested and couldn't reproduce. Actually 4.0.1 is not the latest version it's 4.0.3:
https://bintray.com/epam/reportportal/agent-java-junit5/4.0.3
You can try it on our examples: https://github.com/reportportal/examples-java/tree/rp-4-examples/example-junit5

So I'm going to close this for now. Feel free to reopen if you will still have the issue.

**Closed by HardNorth** 2020-03-27 13:49 UTC
Labels: bug
